pring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

server:
  port: 8082